# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Naive <- function(weight_mat) {
    .Call(`_CHOWLIU_Naive`, weight_mat)
}

Prim_max_cpp <- function(weight_mat) {
    .Call(`_CHOWLIU_Prim_max_cpp`, weight_mat)
}

